config/routes.rb
Rails.application.routes.draw do
  root to: 'static#home'

  get '/admin', to: 'static#admin'
  
  resources :stories do
    resources :branches
  end

  devise_for :users
  resources :users, only: %i[show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/branch.rb
class Branch < ApplicationRecord
  belongs_to :parent, class_name: 'Branch', optional: true
  has_many :branches, foreign_key: 'parent_id'
  belongs_to :story
  belongs_to :user

  validates :title, presence: true
  validates :body, presence: true
  validate :zero_or_one_type

  def zero_or_one_type
    return unless self.end && self.returnable
    errors.add(:base, 'Cannot be returnable and an ending.')
  end
end

app/models/story.rb
class Story < ApplicationRecord
  belongs_to :start_branch, class_name: 'Branch'
  belongs_to :user
  has_many :branches

  accepts_nested_attributes_for :start_branch

  validates :title, presence: true
  validates :description, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :login

  has_many :stories
  has_many :branches
  has_many :forks, through: :branches, source: :story

  validates :name, presence: true, uniqueness: { case_sensitive: false }
  validates_format_of :name, with: /^[a-zA-Z0-9_\.]*$/, multiline: true

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions.to_h).where(['lower(name) = :value OR lower(email) = :value', { value: login.downcase }]).first
    elsif conditions.key?(:name) || conditions.key?(:email)
      where(conditions.to_h).first
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  def require_user
    return head(:forbidden) unless user_signed_in?
  end

  def require_admin
    return head(:forbidden) unless admin?
  end

  def admin?
    user_signed_in? ? current_user.admin : false
  end

  protected

  def configure_permitted_parameters
    added_attrs = [:name, :email, :password, :password_confirmation, :remember_me]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end
end

app/controllers/branches_controller.rb
class BranchesController < ApplicationController
  before_action :set_branch, only: %i[show edit update destroy]
  before_action :require_user, only: %i[create edit update destroy]
  
  def show
    render json: @branch
  end

  def create
    # branch = Branch.create(strong_params)
    # branch.update(story: Story.find(params[:story_id]))
    branch = Branch.new(strong_params)
    branch.user = current_user
    branch.save
    render json: branch
  end

  def edit
    render partial: 'form', locals: { branch: @branch, story: @story }
  end

  def update
    @branch.update(strong_params)
    redirect_to @branch.story
  end

  def destroy
    @branch.destroy
    redirect_to admin_path
  end

  private

  def strong_params
    params
      .require(:branch)
      .permit(:title, :body, :story_id, :parent_id, :end, :returnable)
  end

  def set_branch
    @story = Story.find(params[:story_id])
    @branch = Branch.find(params[:id])
  end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  before_action :require_admin, only: %i[admin]
  def home
  end

  def admin
  end
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  before_action :set_story, only: %i[show edit update destroy]
  before_action :require_user, only: %i[new create]
  before_action :require_right_user, only: %i[edit update destroy]

  helper_method :same_user

  def index
    @stories = Story.all
    respond_to do |format|
      format.html { render :index }
      format.json { render json: @stories }
    end
  end

  def show
  end

  def new
    @story = Story.new
    @branch = @story.build_start_branch
  end

  def create
    story = Story.new(strong_params)
    branch = story.start_branch
    story.user = current_user
    branch.user = current_user
    branch.story = story
    return render :new unless story.save
    redirect_to stories_path
  end

  def edit
    start_branch = @story.start_branch
    render partial: 'form', locals: { story: @story, start_branch: start_branch }
  end

  def update
    @story.update(strong_params)
    redirect_to story
  end

  def destroy
    @story.destroy
    redirect_to stories_path
  end

  private

  def set_story
    @story = Story.find(params[:id])
  end

  def strong_params
    params
      .require(:story)
      .permit :id,
              :title,
              :description,
              start_branch_attributes: %i[id title body]
  end

  def require_right_user
    return head(:forbidden) unless same_user
  end

  def same_user
    @story.user == current_user || admin?
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def errors(resource)
    render partial: 'layouts/error', locals: { resource: resource }
  end

  def render_stars(i)
    render partial: 'reviews/stars', locals: { i: i.floor }
  end

  def admin?
    user_signed_in? ? current_user.admin : false
  end

  def delete_link(resource)
    link_to resource, method: 'delete', data: { confirm: 'Are you sure?' } do
      tag.i class: 'fas fa-trash'
    end
  end

  def fa(name, extra = '', prefix = 'fas')
    tag.i class: "#{prefix} fa-#{name} #{extra}"
  end

  def far(name, extra = '')
    fa name, extra, 'far'
  end

  def date(resource)
    resource.created_at.strftime '%B %-d, %Y'
  end

  def logo
    tag.i class: 'fas fa-share-alt fa-sm',
          data: {
            # 'fa-transform' => 'rotate-270 shrink-5 down-.5',
            'fa-transform' => 'rotate-270',
            # 'fa-mask' => 'fas fa-circle'
          }
  end

  def hb(type, key, &block)
    "{{##{type} #{key}}}
    #{capture(&block)}
    {{/#{type}}}"
  end
end

app/helpers/branches_helper.rb
module BranchesHelper
end

app/helpers/stories_helper.rb
module StoriesHelper
  def story_head(story)
    tag.h1 story.title,
           id: 'storyTitle',
           class: 'mb-0 text-secondary',
           data: {
             id: story.id,
             sbid: story.start_branch.id,
             sbtitle: story.start_branch.title
           }
  end

  def user_badge(user)
    tag.strong do
      link_to user.name, user, class: 'user-link'
    end
  end
end

app/views/branches/_form.slim
= form_for [story, branch] do |f|
  .form-group
    = f.label :title
    = f.text_field :title, class: 'form-control'

  .form-group
    = f.label :body
    = f.text_area :body, class: 'form-control', rows: 5

  .form-check.mb-1
    = f.check_box :end, class: 'form-check-input'
    = f.label :end, 'Ending?', class: 'form-check-label'
  .form-check.mb-1
    = f.check_box :returnable, class: 'form-check-input'
    = f.label :returnable, 'Returnable?', class: 'form-check-label'

  = f.hidden_field :story_id
  = f.hidden_field :parent_id

  = f.submit class: 'btn btn-primary', data: {disable_with: false}

app/views/layouts/_alert.slim
- if message
  .alert.alert-secondary.border-0.d-inline-block.alert-dismissible.fade.show(role="alert")
    = message
    button.close(data-dismiss="alert") = fa 'times', 'fa-xs'

app/views/layouts/_error.slim
- if resource.errors.any?
  .alert.alert-primary.d-inline-block.alert-dismissible.fade.show.border-0(role="alert")
    h5.alert-heading Error
    - resource.errors.full_messages.each do |msg|
      p.mb-0 = msg
    button.close(data-dismiss="alert") = fa 'times', 'fa-xs'

app/views/layouts/_header.slim
nav.navbar.navbar-expand.navbar-dark.mb-3.bg-secondary
  .navbar-nav.align-items-center
    = link_to root_path, class: 'navbar-brand'
      | #{ logo } CYOA

    = link_to 'Stories', stories_path

    - if user_signed_in?
      = link_to current_user, class: 'nav-link'
        | #{ current_user.name }

      .nav-item.dropdown
        = link_to fa('chevron-down fa-sm'), '#', class: 'nav-link', data: {toggle: 'dropdown'}
        .dropdown-menu
          = link_to edit_user_registration_path, class: 'dropdown-item'
            | #{ far 'edit fa-fw' } Edit Account
            
          = link_to destroy_user_session_path, method: 'delete', class: 'dropdown-item'
            | #{ far 'share-square fa-fw'} Sign Out
          
          - if current_user.admin
            .dropdown-divider
            = link_to admin_path, class: 'dropdown-item'
              | #{ far 'clipboard fa-fw' } Admin

    - else
      = link_to 'Sign Up', new_user_registration_path
      = link_to 'Sign In', new_user_session_path

    

app/views/layouts/application.slim
doctype html
html
  head
    meta content=("text/html; charset=UTF-8") http-equiv="Content-Type"

    title Choose Your Own Adventure

    = csrf_meta_tags

    link href="/hind.css" rel="stylesheet"

    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

  body
    = render partial: 'layouts/header'
    
    .container
      = render partial: 'layouts/alert', locals: {message: notice}
      = render partial: 'layouts/alert', locals: {message: alert}

      == yield

app/views/stories/_form.slim
= form_for story do |f|
  .form-group
    = f.label :title
    = f.text_field :title, class: 'form-control'

  .form-group
    = f.label :description
    = f.text_area :description, class: 'form-control'
  
  = f.fields_for :start_branch, start_branch do |b|
    h4 Start Branch
    .form-group
      = b.label :title
      = b.text_field :title, class: 'form-control'

    .form-group
      = b.label :body
      = b.text_area :body, class: 'form-control'

    = b.hidden_field :id

  = f.submit class: 'btn btn-primary'

app/views/stories/index.slim
h1.text-secondary Browse Stories

#none.none
  .row.mb-3
    .col-lg-8
      .card.border-secondary.bg-secondary.text-light
        #curStory.card-body

  .row.mb-3
    .col-lg-4: button.btn.btn-secondary.btn-block#previous #{fa 'angle-left'} Prev
    .col-lg-4: button.btn.btn-secondary.btn-block#next Next #{fa 'angle-right'}

  - if user_signed_in?
    = link_to new_story_path, class: 'btn btn-secondary' do
      => fa 'pencil-alt fa-sm'
      | New Story

^storyDetail
  h4 {{ title }}
  p style="min-height: 6rem" {{ description }}
  h5 {{ endings }}
  a.btn.btn-primary href="{{url}}" Check it Out #{fa 'long-arrow-alt-right fa-lg'}


= javascript_include_tag 'storyIndex'

app/views/stories/new.slim
h1 New Story

= render partial: 'form', locals: {story: @story, start_branch: @branch}

app/views/stories/show.slim
.row.justify-content-between
  .col-md-10
    .mb-2
      = story_head @story
      small by #{ user_badge @story.user } created #{ date @story }

    p = @story.description

  - if same_user
    .col-md-auto.mb-3
      = link_to edit_story_path(@story), class: 'btn btn-secondary btn-block', id: 'editStory'
        | #{ fa 'edit' } Edit
      = link_to @story, method: 'delete', data: { confirm: 'Are you sure?' }, class: 'btn btn-secondary btn-block'
        | #{ fa 'trash' } Delete

#dynamic.none
  #head

  - if user_signed_in?
    button.btn.btn-secondary.btn-sm#toggleForm #{ fa 'pencil-alt fa-sm' } New Branch 

    .row.none#formRow
      .col-lg-8
        .card.border-0.bg-secondary.text-light
          .card-body
            = render partial: 'branches/form', locals: {story: @story, branch: @story.branches.build}

#editModal.modal tabindex="-1" role="dialog"
  .modal-dialog.modal-lg role="document"
    .modal-content
      .modal-body#modalBody

^branchLink
  .mb-1: button.btn.btn-primary id="b-{{ id }}" {{ title }}

^branchHead
  h2.mb-1.text-secondary {{ title }}
  .small.mb-2
    | submitted by
    strong: a.user-link< href="/users/{{user.id}}" {{ user.name }}

  .row
    .col-lg-8
      p == hb 'each', 'body'
        | {{this}}
        br

  == hb 'if', 'returnable'
    .mb-1: button#goBack.btn.btn-link Go Back #{ fa 'undo fa-sm' }

  #branches.mb-3

  == hb 'if', 'end'
    h2.text-primary The End
    .mb-3
      button#startOver.btn.btn-primary #{ fa 'sync fa-sm' } Start Over

  == hb 'if', 'same_user'
    .mb-3
      button#editBranch.btn.btn-secondary.btn-sm #{ fa 'edit' } Edit
  
= javascript_include_tag 'storyShow'

app/views/users/show.slim
.card.d-inline-block.border-0.bg-secondary.text-light.mb-3
  .card-body
    h1 #{ fa 'user fa-xs' } #{ @user.name }
    | Joined #{ date @user }

.row
  .col
    h3.blue-heading Stories Created
    - if @user.stories.empty?
      br
      small this user has created no stories

    / ul.list-group
    /   - @user.stories.each do |story|
    /     li.list-group-item: strong = link_to story.title, story 
    - @user.stories.each do |story|
      .mb-2 = link_to story, class: 'btn btn-outline-dark'
        strong = story.title
        
  .col
    h3.blue-heading Stories Contributed To
    / ul.list-group
    /   - @user.forks.distinct.each do |story|
    /     li.list-group-item
    /       strong = link_to story.title, story
    /       br
    /       small #{story.branches.where(user_id: @user.id).count} branches
    - @user.forks.distinct.each do |story|
      .mb-2 = link_to story, class: 'btn btn-outline-dark text-left'
        strong = story.title
        br
        small #{story.branches.where(user_id: @user.id).count} branches